"" general
set number
set linebreak		    " break lines at word (requires wrap lines)
set textwidth=1000	    " line wrap (number of cols)
set showmatch		    " highlight matching brace
set cursorline		    " highlight current line 
set hlsearch		    " highlight all search results
set smartcase		    " enable smart-case search
set ignorecase		    " always case-insensitive
set incsearch		    " searches for strings incrementally
set autoindent		    " auto-indent new lines
set shiftwidth=4	    " number of auto-indent spaces
set smartindent		    " enable smart-indent
set smarttab		    " enable smart-tabs
set softtabstop=4	    " number of spaces per tab
"set ruler		    " show row and column ruler information
set undolevels=1000	    " number of undo levels
set wildmenu		    " autocomplete
set wildmode=list:longest   " more autocomplete
set linespace=2		    " linespace
set display+=lastline	    " display last line of buffer
set guifont=Liberation\ Mono\ 14 " set gui font
colorscheme xcode	    " set highlight scheme 


" remap df to esc and save file (if in insert mode), or save if in normal mode 
inoremap df  <ESC>:w<CR>	   
nnoremap df  :w<CR>	   

